[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T13:21:31"
timestamp_intended_ISO = "2025-03-12T13:21:31"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T19:12:00"
timestamp_intended_ISO = "2025-03-12T19:12:00"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T19:35:31"
timestamp_intended_ISO = "2025-03-12T19:35:31"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T19:38:18"
timestamp_intended_ISO = "2025-03-12T19:38:18"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0
operator = "CB"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T21:50:12"
timestamp_intended_ISO = "2025-03-12T21:49:46"
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"
north_basin_1_MGD = 1.0
north_basin_3_MGD = 1.0
north_basin_5_MGD = 1.0
north_basin_7_MGD = 1.0
north_basin_9_MGD = 1.0
north_basin_11_MGD = 1.0
north_basin_13_MGD = 1.0
south_basin_1_MGD = 1.0
south_basin_3_MGD = 1.0
south_basin_5_MGD = 1.0
south_basin_7_MGD = 1.0
south_basin_9_MGD = 1.0
south_basin_11_MGD = 1.0
south_basin_13_MGD = 1.0
north_clarifier_1_MGD = 1.0
north_clarifier_2_MGD = 1.0
north_clarifier_3_MGD = 1.0
north_clarifier_4_MGD = 1.0
south_clarifier_1_MGD = 1.0
south_clarifier_2_MGD = 1.0
south_clarifier_3_MGD = 1.0
south_clarifier_4_MGD = 1.0
north_ras_1_MGD = 1.0
north_ras_2_MGD = 1.0
north_ras_3_MGD = 1.0
north_ras_4_MGD = 11.0
south_ras_1_MGD = 1.0
south_ras_2_MGD = 11.0
south_ras_3_MGD = 1.0
south_ras_4_MGD = 1.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T21:59:20"
timestamp_intended_ISO = "2025-03-12T21:59:20"
operator = "CB"
source = "web-post-Python-FastAPI"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:21:01"
timestamp_intended_ISO = "2025-03-13T08:21:01"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:22:27"
timestamp_intended_ISO = "2025-03-13T08:22:27"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:23:38"
timestamp_intended_ISO = "2025-03-13T08:23:38"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:32:47"
timestamp_intended_ISO = "2025-03-13T08:32:47"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:34:09"
timestamp_intended_ISO = "2025-03-13T08:34:09"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T11:36:26"
timestamp_intended_ISO = "2025-03-13T11:36:10"
operator = "CB"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0
north_basin_3_MGD = 1.0
north_basin_5_MGD = 1.0
north_basin_7_MGD = 1.0
north_basin_9_MGD = 1.0
north_basin_11_MGD = 1.0
north_basin_13_MGD = 1.0
south_basin_1_MGD = 1.0
south_basin_3_MGD = 1.0
south_basin_5_MGD = 1.0
south_basin_7_MGD = 1.0
south_basin_9_MGD = 1.0
south_basin_11_MGD = 1.0
south_basin_13_MGD = 1.0
north_clarifier_1_MGD = 1.0
north_clarifier_2_MGD = 1.0
north_clarifier_3_MGD = 1.0
north_clarifier_4_MGD = 1.0
south_clarifier_1_MGD = 1.0
south_clarifier_2_MGD = 1.0
south_clarifier_3_MGD = 1.0
south_clarifier_4_MGD = 1.0
north_ras_1_MGD = 1.0
north_ras_2_MGD = 111.0
north_ras_3_MGD = 1.0
north_ras_4_MGD = 1.0
south_ras_1_MGD = 1.0
south_ras_2_MGD = 1.0
south_ras_3_MGD = 1.0
south_ras_4_MGD = 11.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T12:31:59"
timestamp_intended_ISO = "2025-03-13T12:31:55"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T12:32:14"
timestamp_intended_ISO = "2025-03-13T12:31:55"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T12:32:27"
timestamp_intended_ISO = "2025-03-13T12:31:55"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T12:32:34"
timestamp_intended_ISO = "2025-03-13T12:31:55"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T12:41:49"
timestamp_intended_ISO = "2025-03-13T12:41:38"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0
north_basin_3_MGD = 2.0
north_basin_5_MGD = 3.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T12:43:27"
timestamp_intended_ISO = "2025-03-13T12:43:25"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T13:05:12"
timestamp_intended_ISO = "2025-03-13T12:41:38"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0
north_basin_3_MGD = 2.0
north_basin_5_MGD = 3.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T13:11:40"
timestamp_intended_ISO = "2025-03-13T13:11:39"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T13:14:05"
timestamp_intended_ISO = "2025-03-13T13:13:55"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:39:06"
timestamp_intended_ISO = "2025-03-13T14:38:00"
operator = "CB"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:39:21"
operator = "CB"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:39:36"
timestamp_intended_ISO = "2025-03-13T14:00:00"
operator = "CB"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:40:28"
operator = "CB"
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 0.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T08:29:37"
timestamp_intended_ISO = "2025-03-14T08:29:22"
operator = ""
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 1.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T12:42:51"
timestamp_intended_ISO = "2025-03-14T12:42:51"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 1.0
north_basin_3_MGD = 1.0
north_basin_5_MGD = 1.0
north_basin_7_MGD = 1.0
north_basin_9_MGD = 1.0
north_basin_11_MGD = 1.0
north_basin_13_MGD = 1.0
south_basin_1_MGD = 1.0
south_basin_3_MGD = 1.0
south_basin_5_MGD = 1.0
south_basin_7_MGD = 1.0
south_basin_9_MGD = 1.0
south_basin_11_MGD = 1.0
south_basin_13_MGD = 1.0
north_clarifier_1_MGD = 1.0
north_clarifier_2_MGD = 2.0
north_clarifier_3_MGD = 2.0
north_clarifier_4_MGD = 2.0
south_clarifier_1_MGD = 2.0
south_clarifier_2_MGD = 2.0
south_clarifier_3_MGD = 2.0
south_clarifier_4_MGD = 2.0
north_ras_1_MGD = 2.0
north_ras_2_MGD = 2.0
north_ras_3_MGD = 2.0
north_ras_4_MGD = 2.0
south_ras_1_MGD = 2.0
south_ras_2_MGD = 2.0
south_ras_3_MGD = 2.0
south_ras_4_MGD = 2.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T12:52:01"
timestamp_intended_ISO = "2025-03-14T12:52:01"
operator = "CB"
source = "local-shell-Python-cmd2"
north_basin_1_MGD = 1.0
north_basin_3_MGD = 1.0
north_basin_5_MGD = 1.0
north_basin_7_MGD = 1.0
north_basin_9_MGD = 1.0
north_basin_11_MGD = 1.0
north_basin_13_MGD = 1.0
south_basin_1_MGD = 1.0
south_basin_3_MGD = 1.0
south_basin_5_MGD = 1.0
south_basin_7_MGD = 1.0
south_basin_9_MGD = 1.0
south_basin_11_MGD = 1.0
south_basin_13_MGD = 1.0
north_clarifier_1_MGD = 1.0
north_clarifier_2_MGD = 2.0
north_clarifier_3_MGD = 2.0
north_clarifier_4_MGD = 2.0
south_clarifier_1_MGD = 2.0
south_clarifier_2_MGD = 2.0
south_clarifier_3_MGD = 2.0
south_clarifier_4_MGD = 2.0
north_ras_1_MGD = 2.0
north_ras_2_MGD = 2.0
north_ras_3_MGD = 2.0
north_ras_4_MGD = 2.0
south_ras_1_MGD = 2.0
south_ras_2_MGD = 2.0
south_ras_3_MGD = 2.0
south_ras_4_MGD = 2.0

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T13:13:51"
timestamp_intended_ISO = "2025-03-14T13:13:33"
operator = ""
source = "local-gui-Python-FreeSimpleGUI"
north_basin_1_MGD = 99.0

