[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:51:50"
timestamp_intended_ISO = "2025-03-11T14:51:47"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:52:00"
timestamp_intended_ISO = "2025-03-11T14:51:47"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T12:09:34"
timestamp_intended_ISO = "2025-03-12T12:09:32"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T12:16:45"
timestamp_intended_ISO = "2025-03-12T12:16:11"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T12:17:45"
timestamp_intended_ISO = "2025-03-12T12:17:37"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T12:20:04"
timestamp_intended_ISO = "2025-03-12T12:19:56"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T19:33:42"
timestamp_intended_ISO = "2025-03-12T19:33:42"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0
operator = "CB"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T19:37:38"
timestamp_intended_ISO = "2025-03-12T19:37:38"
north_basin_1_MGD = 0.0
north_basin_3_MGD = 0.0
north_basin_5_MGD = 0.0
north_basin_7_MGD = 0.0
north_basin_9_MGD = 0.0
north_basin_11_MGD = 0.0
north_basin_13_MGD = 0.0
south_basin_1_MGD = 0.0
south_basin_3_MGD = 0.0
south_basin_5_MGD = 0.0
south_basin_7_MGD = 0.0
south_basin_9_MGD = 0.0
south_basin_11_MGD = 0.0
south_basin_13_MGD = 0.0
north_clarifier_1_MGD = 0.0
north_clarifier_2_MGD = 0.0
north_clarifier_3_MGD = 0.0
north_clarifier_4_MGD = 0.0
south_clarifier_1_MGD = 0.0
south_clarifier_2_MGD = 0.0
south_clarifier_3_MGD = 0.0
south_clarifier_4_MGD = 0.0
north_ras_1_MGD = 0.0
north_ras_2_MGD = 0.0
north_ras_3_MGD = 0.0
north_ras_4_MGD = 0.0
south_ras_1_MGD = 0.0
south_ras_2_MGD = 0.0
south_ras_3_MGD = 0.0
south_ras_4_MGD = 0.0
operator = "CB"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-12T20:35:35"
timestamp_intended_ISO = "2025-03-12T20:35:25"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:30:29"
timestamp_intended_ISO = "2025-03-13T15:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:30:33"
timestamp_intended_ISO = "2025-03-13T15:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:32:54"
timestamp_intended_ISO = "2025-03-13T15:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:32:58"
timestamp_intended_ISO = "2025-03-13T15:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:33:51"
timestamp_intended_ISO = "2025-03-13T15:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T08:33:55"
timestamp_intended_ISO = "2025-03-13T15:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T13:10:59"
timestamp_intended_ISO = "2025-03-13T13:10:50"
safe_to_make_observation = "Yes"
floatable_present = "Yes"
scum_present = "Yes"
foam_present = "Yes"
oil_present = "Yes"
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T13:13:31"
timestamp_intended_ISO = "2025-03-13T13:13:21"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = false
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T13:38:49"
timestamp_intended_ISO = "2025-03-13T13:38:37"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = true
oil_present = false
operator = "JT"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:06:55"
timestamp_intended_ISO = "2025-03-13T12:06:31"
safe_to_make_observation = true
floatable_present = false
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:50:40"
timestamp_intended_ISO = "2025-03-13T14:50:31"
safe_to_make_observation = true
floatable_present = false
scum_present = true
foam_present = false
oil_present = true
operator = "CB"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:52:11"
timestamp_intended_ISO = "2025-03-13T14:51:47"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "CB"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:55:09"
timestamp_intended_ISO = "2025-03-13T14:55:09"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:55:33"
timestamp_intended_ISO = "2025-03-13T15:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T14:55:33"
timestamp_intended_ISO = "2025-03-13T14:55:33"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T15:17:37"
timestamp_intended_ISO = "2025-03-13T15:17:37"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-13T15:22:31"
timestamp_intended_ISO = "2025-03-13T15:22:31"
safe_to_make_observation = true
floatable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "local-shell-Python-cmd2"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T13:13:13"
timestamp_intended_ISO = "2025-03-14T13:13:01"
safe_to_make_observation = true
floatable_present = false
scum_present = false
foam_present = false
oil_present = true
operator = "HN"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T13:13:18"
timestamp_intended_ISO = "2025-03-14T13:13:01"
safe_to_make_observation = true
floatable_present = false
scum_present = false
foam_present = false
oil_present = true
operator = "HN"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T13:18:16"
timestamp_intended_ISO = "2025-03-14T11:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "SB"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T13:18:43"
timestamp_intended_ISO = "2025-03-14T11:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "SB"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-14T13:36:56"
timestamp_intended_ISO = "2025-03-14T11:00:00"
safe_to_make_observation = true
floatable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "SB"
source = "local-gui-Python-FreeSimpleGUI"

[[flows_and_cod_hourly_data]]
timestamp_entry_ISO = "2025-03-14T18:00:13"
timestamp_intended_ISO = "2025-03-14T17:59:59"
safe_to_make_observation = true
floatable_present = false
scum_present = true
foam_present = false
oil_present = true
operator = "CB"
source = "local-gui-Python-FreeSimpleGUI"

